### ISSUE TITLE
IPS framework install on NERSC software directory

### ISSUE THREAD

**Issue by parkjm** [ORNL-Fusion/ips-wrappers#50]
@elwasif Would you please install ips-framework under /global/common/software/atom/ips? The area /global/common/software/atom is the suggested new directory for the IPS workflows.

**Comment by elwasif** [comment]
@parkjm I've installed the master branch there, which requires Python3

**Comment by batchelordb** [comment]
Wael;

I’ve cloned the master branch to my mac.  It comes with build instructions.  Does anything actually need to be built?

DBB



On Apr 20, 2020, at 2:46 PM, Wael Elwasif <notifications@github.com<mailto:notifications@github.com>> wrote:



@parkjm<https://github.com/parkjm> I've installed the master branch there, which requires Python3

**Comment by elwasif** [comment]
Technically, no. As we do in the ips-wrappers  env.ips and the instructions in the ips-examples

export IPS_PATH=$IPS_DIR/ips-framework
export PATH=$IPS_PATH/framework/src:$PATH

and you're good to go.

Wael

--
Wael R. Elwasif, PhD.
Research Staff Member
Computer Science Research Group
Oak Ridge National Laboratory
P.O. Box 2008, Bldg. 5600, MS 6016
Oak Ridge, TN 37831-6016

Office : (865)241-0002
Fax: (865)576-5491
________________________________
